// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9EUcIxrzcfGSo1ipBWa9y2xWsaG47BJU',
    appId: '1:165814680401:web:957867a21ed181bb387170',
    messagingSenderId: '165814680401',
    projectId: 'boldo-81d2e',
    authDomain: 'boldo-81d2e.firebaseapp.com',
    storageBucket: 'boldo-81d2e.firebasestorage.app',
    measurementId: 'G-EVW1C8QVXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMk9OQVQ8bxC8p97RF3EXZhpYfsb_J508',
    appId: '1:165814680401:android:98dbc9fa05b48d8a387170',
    messagingSenderId: '165814680401',
    projectId: 'boldo-81d2e',
    storageBucket: 'boldo-81d2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQFhx59gu19ewPdCa6CodNicySE2QMfxI',
    appId: '1:165814680401:ios:aa6f57f89c7c692a387170',
    messagingSenderId: '165814680401',
    projectId: 'boldo-81d2e',
    storageBucket: 'boldo-81d2e.firebasestorage.app',
    iosBundleId: 'com.example.boldo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQFhx59gu19ewPdCa6CodNicySE2QMfxI',
    appId: '1:165814680401:ios:aa6f57f89c7c692a387170',
    messagingSenderId: '165814680401',
    projectId: 'boldo-81d2e',
    storageBucket: 'boldo-81d2e.firebasestorage.app',
    iosBundleId: 'com.example.boldo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9EUcIxrzcfGSo1ipBWa9y2xWsaG47BJU',
    appId: '1:165814680401:web:152b52574a04f536387170',
    messagingSenderId: '165814680401',
    projectId: 'boldo-81d2e',
    authDomain: 'boldo-81d2e.firebaseapp.com',
    storageBucket: 'boldo-81d2e.firebasestorage.app',
    measurementId: 'G-L8KQB1SYWJ',
  );
}
